### ISSUE TITLE
Legacy Packages

### ISSUE THREAD

**Issue by michaelstaib** [chandsalam1108/GraphQLAzFunctionNet5#1]
Hi there,

great post!

Just two things,

the following packages are legacy packages which we soon no longer support:
    <PackageReference Include="HotChocolate.Types.Filters" Version="11.3.0" />
    <PackageReference Include="HotChocolate.Types.Selections" Version="11.0.0-preview.138" />
    <PackageReference Include="HotChocolate.Types.Sorting" Version="11.3.0" />
    
The functionallity was moved into the package HotChocolate.Data.

You can simplify the project file. You actually only need two packages, HotChocolate.AspNetCore and HotChocolate.Data.

**Comment by chandsalam1108** [comment]
Dear Michael,

Thank you so much for sharing your observations.

As of now I'm using following packages and I found it has simplified the have we query from dependent tables using projections. 

Using projections, I believe we can avoid using Resolvers & DataLoaders to fetch data from dependent tables.

Hope I've understood that correctly.

<PackageReference Include="HotChocolate.AspNetCore" Version="11.3.0" />
<PackageReference Include="HotChocolate.Data.EntityFramework" Version="11.3.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.7">

Thanks,
Chand.

**Comment by chandsalam1108** [comment]
Updated by removing legacy packages.
